### ISSUE TITLE
PySimpleGUI's Save To / Load From Disk

### ISSUE THREAD

**Issue by MikeTheWatchGuy** [Rubber-Duck-999/RocketSimulator#8]
Hiya.... I noticed you're using the calls window.SaveToDisk(filename) and window.LoadFromDisk(filename).  I don't know if those calls are still working.  It's been a while since they were tested.  If you run into trouble, please open an Issue on the PySimpleGUI GitHub site.  I was just thinking today of perhaps removing that feature since it's not often used and it's possible for users to do this in their own code.

Hopefully it is still working without trouble.  Didn't want to see you banging your head against the wall thinking you're doing something wrong if there is a problem.

**Comment by Rubber-Duck-999** [comment]
Wow, thanks. Ill take a look at the update but for now I will nullify its use.

**Comment by Rubber-Duck-999** [comment]
Moved to sprint 2 deadline backlog

**Comment by Rubber-Duck-999** [comment]
Function calls were removed, console doesn't require the save/load in PGui

**Comment by PySimpleGUI** [comment]
I think I fixed this after finding you using it,  Would have to check release notes to be sure.

**Comment by PySimpleGUI** [comment]
For what it's worth....

Oh!  If you have any screenshots, I've noticed that people stop into the repository when there are some present in the readme.  I mentioned to several PySimpleGUI based projects in the past and they saw more traffic, stars, etc, as a result (probably?).  I know I tend to stop and look when I can see what the program does.
